#pragma once
// Generated by tools/ref_primitives.py; do not edit.
struct PrimOp { const char* kind; int n; double v[16]; int fill, outline, width; };
struct PrimCase { const char* name; int n_ops; PrimOp ops[3]; };
static const int PRIM_W = 120, PRIM_H = 80;
static const PrimCase PRIM_CASES[] = {
    {"line_w1_diag", 1, {{"line", 4, {5.5, 10.2, 110.7, 70.9}, 0, -1, 1}}},
    {"line_w2_diag", 1, {{"line", 4, {5.5, 10.2, 110.7, 70.9}, 0, -1, 2}}},
    {"line_w3_diag", 1, {{"line", 4, {5.5, 70.2, 110.7, 10.9}, 0, -1, 3}}},
    {"line_w5_steep", 1, {{"line", 4, {40.3, 5.0, 60.8, 75.0}, 0, -1, 5}}},
    {"line_w2_horizontal", 1, {{"line", 4, {10.0, 40.0, 110.0, 40.0}, 0, -1, 2}}},
    {"line_w4_vertical", 1, {{"line", 4, {60.0, 5.0, 60.0, 75.0}, 0, -1, 4}}},
    {"line_short_dash", 1, {{"line", 4, {20.25, 30.5, 26.75, 33.1}, 0, -1, 2}}},
    {"line_white_on_black", 2, {{"rectangle", 4, {0.0, 0.0, 119.0, 79.0}, 0, -1, 1}, {"line", 4, {5.0, 5.0, 115.0, 75.0}, 255, -1, 3}}},
    {"polyline_w1", 1, {{"line", 8, {10.0, 60.0, 40.0, 20.5, 70.2, 65.0, 110.0, 15.0}, 0, -1, 1}}},
    {"polyline_w2", 1, {{"line", 8, {10.0, 60.0, 40.0, 20.5, 70.2, 65.0, 110.0, 15.0}, 0, -1, 2}}},
    {"polyline_w3", 1, {{"line", 8, {10.0, 60.0, 40.0, 20.5, 70.2, 65.0, 110.0, 15.0}, 0, -1, 3}}},
    {"polyline_icon", 1, {{"line", 8, {70.4, 40.2, 66.6, 48.7, 74.4, 48.7, 70.6, 58.9}, 0, -1, 3}}},
    {"points_dotted", 1, {{"points", 4, {10.0, 110.0, 6.0, 40.5}, 0, -1, 1}}},
    {"rect_fill_float", 1, {{"rectangle", 4, {10.4, 10.6, 30.2, 30.9}, 0, -1, 1}}},
    {"rect_white_on_black", 2, {{"rectangle", 4, {0.0, 0.0, 119.0, 79.0}, 0, -1, 1}, {"rectangle", 4, {20.0, 20.0, 60.0, 50.0}, 255, -1, 1}}},
    {"ellipse_outline_w3", 1, {{"ellipse", 4, {10.0, 10.0, 90.0, 60.0}, -1, 0, 3}}},
    {"ellipse_outline_float_w4", 1, {{"ellipse", 4, {10.3, 5.6, 50.9, 44.2}, -1, 0, 4}}},
    {"ellipse_outline_w2_small", 1, {{"ellipse", 4, {20.5, 20.5, 31.5, 31.5}, -1, 0, 2}}},
    {"ellipse_fill_black", 1, {{"ellipse", 4, {80.0, 40.0, 119.0, 79.0}, 0, -1, 1}}},
    {"ellipse_marker", 2, {{"line", 4, {0.0, 40.0, 119.0, 40.0}, 0, -1, 3}, {"ellipse", 4, {55.0, 35.0, 65.0, 45.0}, 255, 0, 2}}},
    {"ellipse_cloud", 2, {{"ellipse", 4, {20.6, 18.2, 60.6, 58.2}, -1, 0, 3}, {"ellipse", 4, {23.6, 21.2, 57.6, 55.2}, 255, -1, 1}}},
    {"polygon_triangle", 1, {{"polygon", 6, {33.7, 36.2, 38.7, 45.2, 28.7, 45.2}, 0, -1, 1}}},
    {"polygon_diamond", 2, {{"line", 4, {0.0, 32.0, 119.0, 32.0}, 0, -1, 2}, {"polygon", 8, {60.0, 20.0, 72.0, 32.0, 60.0, 44.0, 48.0, 32.0}, 255, 0, 2}}},
    {"rounded_small", 1, {{"rounded_rectangle", 5, {10.5, 10.0, 60.5, 32.0, 4.0}, 0, -1, 1}}},
    {"rounded_float", 1, {{"rounded_rectangle", 5, {70.3, 40.1, 110.6, 62.9, 4.0}, 0, -1, 1}}},
    {"neg_line_w5", 1, {{"line", 4, {-14.72, 24.0, 136.65, 77.6}, 0, -1, 5}}},
    {"neg_ellipse_outline_w4", 1, {{"ellipse", 4, {-9.75, 14.0, 30.25, 63.2}, -1, 0, 4}}},
    {"neg_polygon_rounded", 2, {{"polygon", 6, {-12.6, 70.4, 40.3, -8.7, 60.2, 75.5}, 0, -1, 1}, {"rounded_rectangle", 5, {-6.5, -3.5, 30.5, 20.5, 6.0}, 255, -1, 1}}},
};
