#pragma once
// Generated by tools/gen_fonts.py; do not edit.
#include "render/fonts/dejavu_sans_10.h"
#include "render/fonts/dejavu_sans_11.h"
#include "render/fonts/dejavu_sans_12.h"
#include "render/fonts/dejavu_sans_13.h"
#include "render/fonts/dejavu_sans_14.h"
#include "render/fonts/dejavu_sans_15.h"
#include "render/fonts/dejavu_sans_18.h"
#include "render/fonts/dejavu_sans_bold_8.h"
#include "render/fonts/dejavu_sans_bold_11.h"
#include "render/fonts/dejavu_sans_bold_12.h"
#include "render/fonts/dejavu_sans_bold_13.h"
#include "render/fonts/dejavu_sans_bold_14.h"
#include "render/fonts/dejavu_sans_bold_15.h"
#include "render/fonts/dejavu_sans_bold_17.h"
#include "render/fonts/dejavu_sans_bold_18.h"
#include "render/fonts/dejavu_sans_bold_20.h"
#include "render/fonts/dejavu_sans_bold_22.h"
#include "render/fonts/dejavu_sans_bold_26.h"
#include "render/fonts/dejavu_sans_bold_36.h"
#include "render/fonts/dejavu_sans_bold_46.h"

namespace ink::fonts {
inline constexpr const Font* ALL[] = {
    &dejavu_sans_10,
    &dejavu_sans_11,
    &dejavu_sans_12,
    &dejavu_sans_13,
    &dejavu_sans_14,
    &dejavu_sans_15,
    &dejavu_sans_18,
    &dejavu_sans_bold_8,
    &dejavu_sans_bold_11,
    &dejavu_sans_bold_12,
    &dejavu_sans_bold_13,
    &dejavu_sans_bold_14,
    &dejavu_sans_bold_15,
    &dejavu_sans_bold_17,
    &dejavu_sans_bold_18,
    &dejavu_sans_bold_20,
    &dejavu_sans_bold_22,
    &dejavu_sans_bold_26,
    &dejavu_sans_bold_36,
    &dejavu_sans_bold_46};
}  // namespace ink::fonts
