#pragma once
// Generated by tools/record_fixtures.py; do not edit.
#define FIXTURE_TODAY 20726  // 2026-09-30
#define FIXTURE_NOW 1790787600LL  // 2026-09-30T10:00:00-07:00
#define FIXTURE_TAIL_S0 20604  // 2026-05-31
#define FIXTURE_FULL_START 17012  // 2016-07-30
