#!/usr/bin/env bash
# Regenerate include/ca_certs.h from the system trust store (spec §6.1): the roots that
# Cloudflare's edge certificates chain to (Let's Encrypt, Google Trust Services, SSL.com).
set -euo pipefail
cd "$(dirname "$0")/.."
certs=(ISRG_Root_X1 ISRG_Root_X2 GTS_Root_R1 GTS_Root_R4 SSL.com_Root_Certification_Authority_ECC)
{
  echo "#pragma once"
  echo "// Generated by tools/gen_ca_certs.sh; do not edit."
  echo "// Root CAs for Cloudflare's edge certificates: ${certs[*]}"
  echo "static const char CA_BUNDLE_PEM[] ="
  for c in "${certs[@]}"; do
    echo "    // $c"
    sed 's/.*/    "&\\n"/' "/etc/ssl/certs/$c.pem"
  done
  echo "    ;"
} > include/ca_certs.h
echo "wrote include/ca_certs.h (${#certs[@]} roots)"
