# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""IANA zone -> POSIX TZ rule for include/tz_table.h (spec §2.2), from the footer of each
TZif file in the system tzdata, plus test/test_data/tz_cases.h with expected local times
from Python's zoneinfo. Run: uv run tools/gen_tz_table.py
The footer must be right from today on (zones that switched rules earlier, e.g. to permanent
time, are fine); regenerate when tzdata changes.
"""
import calendar
import re
import zoneinfo
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TABLE = ROOT / "include" / "tz_table.h"
CASES = ROOT / "test" / "test_data" / "tz_cases.h"
CASE_ZONES = ["UTC", "America/Los_Angeles", "America/New_York", "Europe/London", "Asia/Kolkata",
              "Asia/Kathmandu", "Australia/Lord_Howe", "Australia/Sydney", "Pacific/Chatham",
              "America/Nuuk", "America/Sao_Paulo"]
EPOCH = datetime(1970, 1, 1, tzinfo=timezone.utc)
TODAY = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
CHECK_FROM, CHECK_TO = TODAY, TODAY + timedelta(days=4 * 365 + 1)
NAME = r"(<[^>]*>|[A-Za-z]{3,})"
OFFSET = r"([+-]?\d+(?::\d+){0,2})"
RULE = re.compile(NAME + OFFSET + r"(?:" + NAME + OFFSET + r"?,([^,]+),([^,]+))?")
TRANS = re.compile(r"(?:M(\d+)\.(\d+)\.(\d+)|J(\d+)|(\d+))(?:/([+-]?\d+(?::\d+){0,2}))?")


def hms(text: str) -> int:
    sign = -1 if text.startswith("-") else 1
    parts = [int(x) for x in text.lstrip("+-").split(":")] + [0, 0]
    return sign * (parts[0] * 3600 + parts[1] * 60 + parts[2])


def transition(spec: str, year: int) -> int:
    """Seconds from the epoch to the local wall time of a POSIX transition (as include/tz.h)."""
    m = TRANS.fullmatch(spec)
    t = hms(m.group(6)) if m.group(6) else 7200
    if m.group(1):
        mon, week, wd = int(m.group(1)), int(m.group(2)), int(m.group(3))
        first = date(year, mon, 1)
        d = first + timedelta(days=(wd - (first.weekday() + 1) % 7) % 7 + (week - 1) * 7)
        while d.month != mon:
            d -= timedelta(days=7)
    elif m.group(4):
        n = int(m.group(4))
        d = date(year, 1, 1) + timedelta(days=n - 1 + (1 if calendar.isleap(year) and n >= 60 else 0))
    else:
        d = date(year, 1, 1) + timedelta(days=int(m.group(5)))
    return (d - EPOCH.date()).days * 86400 + t


def posix_offset(rule: str, t: int) -> int | None:
    m = RULE.fullmatch(rule)
    if not m:
        return None
    std = -hms(m.group(2))
    if not m.group(3):
        return std
    dst = -hms(m.group(4)) if m.group(4) else std + 3600
    y = (EPOCH + timedelta(seconds=t + std)).year
    start, end = transition(m.group(5), y) - std, transition(m.group(6), y) - dst
    in_dst = start <= t < end if start < end else not (end <= t < start)
    return dst if in_dst else std


def footer_matches(name: str, rule: str) -> bool:
    """True if the footer rule gives zoneinfo's offsets over CHECK_FROM..CHECK_TO (3-hour steps).
    False for zones with transitions the rule cannot express, e.g. Africa/Casablanca's Ramadan."""
    tz = zoneinfo.ZoneInfo(name)
    t = CHECK_FROM
    while t < CHECK_TO:
        if posix_offset(rule, int(t.timestamp())) != int(t.astimezone(tz).utcoffset().total_seconds()):
            return False
        t += timedelta(hours=3)
    return True


def footer(name: str) -> str | None:
    for base in zoneinfo.TZPATH:
        p = Path(base) / name
        if p.is_file():
            data = p.read_bytes()
            if not data.startswith(b"TZif") or data[4:5] not in (b"2", b"3", b"4"):
                return None
            rule = data.rstrip(b"\n").rsplit(b"\n", 1)[-1].decode("ascii")
            return rule or None
    return None


def next_top_of_hour(now: datetime, tz) -> datetime:  # server/inkboard_server/schedule.py
    t = now.astimezone(timezone.utc).replace(second=0, microsecond=0)
    t = t.replace(minute=t.minute - t.minute % 15)
    while True:
        t += timedelta(minutes=15)
        local = t.astimezone(tz)
        if local.minute == 0 and t > now:
            return local


def main() -> None:
    entries, excluded = [], []
    for name in sorted(zoneinfo.available_timezones()):
        rule = footer(name)
        if not rule or name.startswith(("posix/", "right/")) or name in ("Factory", "localtime"):
            continue
        (entries if footer_matches(name, rule) else excluded).append((name, rule))
    body = "\n".join(f'    {{"{n}", "{r}"}},' for n, r in entries)
    TABLE.write_text(
        "#pragma once\n// Generated by tools/gen_tz_table.py from the system tzdata; do not edit.\n"
        "// Regenerate (and reflash) when a zone's rules change.\n\nnamespace ink::tz {\n\n"
        "struct Entry {\n  const char* name;\n  const char* rule;\n};\n\n"
        f"inline constexpr Entry TABLE[] = {{\n{body}\n}};\n\n}}  // namespace ink::tz\n")
    rows = []
    for zname in CASE_ZONES:
        tz = zoneinfo.ZoneInfo(zname)
        start = TODAY
        instants = set()
        prev = start.astimezone(tz).utcoffset()
        t = start
        while t < datetime(2029, 1, 1, tzinfo=timezone.utc):
            off = t.astimezone(tz).utcoffset()
            if off != prev:
                for k in range(-12, 13):
                    instants.add(t + timedelta(minutes=15 * k) - timedelta(minutes=30))
                prev = off
            if t.hour == 0 and t.weekday() == 2:
                instants.add(t + timedelta(minutes=7))
            t += timedelta(hours=1)
        for t in sorted(instants):
            local = t.astimezone(tz)
            epoch = int((t - EPOCH).total_seconds())
            day = (local.date() - EPOCH.date()).days
            nxt = int((next_top_of_hour(t, tz) - EPOCH).total_seconds())
            rows.append(f'    {{"{zname}", {epoch}, {day}, {local.hour}, {local.minute}, '
                        f'{int(local.utcoffset().total_seconds())}, {nxt}}},')
    CASES.write_text(
        "#pragma once\n// Generated by tools/gen_tz_table.py from Python's zoneinfo; do not edit.\n"
        "#include <stdint.h>\n"
        "struct TzCase { const char* zone; int64_t epoch; int32_t day; int hh, mm; int32_t offset; int64_t next_top; };\n"
        "static const TzCase TZ_CASES[] = {\n" + "\n".join(rows) + "\n};\n")
    print(f"{len(entries)} zones, {len(rows)} cases; left out (rules the footer cannot express): "
          + ", ".join(n for n, _ in excluded))


if __name__ == "__main__":
    main()
