# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow==12.3.0"]
# ///
"""Reference images for include/render/canvas.h (plan Task 4).

Each case is drawn by Pillow the way the server drew (mode "L", fills 0/255, threshold 140,
then mode "1"), saved as test/reference/primitives/<name>.pbm, and listed in
test/test_render/prim_cases.h so the C++ test replays exactly the same operations.
Run: uv run tools/ref_primitives.py
"""
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "test/reference/primitives"
HEADER = ROOT / "test/test_render/prim_cases.h"
W, H = 120, 80
THRESHOLD = 140

# (kind, numbers, fill, outline, width). fill/outline: 0 black, 255 white, -1 none.
# line: x0 y0 x1 y1 [x2 y2 ...]; points: x_from x_to step y (range(int, int, int) at y);
# rectangle/ellipse: x0 y0 x1 y1; polygon: x0 y0 x1 y1 ...; rounded_rectangle: x0 y0 x1 y1 r.
BLACK_BG = ("rectangle", [0, 0, W - 1, H - 1], 0, -1, 1)
CASES = {
    "line_w1_diag": [("line", [5.5, 10.2, 110.7, 70.9], 0, -1, 1)],
    "line_w2_diag": [("line", [5.5, 10.2, 110.7, 70.9], 0, -1, 2)],
    "line_w3_diag": [("line", [5.5, 70.2, 110.7, 10.9], 0, -1, 3)],
    "line_w5_steep": [("line", [40.3, 5.0, 60.8, 75.0], 0, -1, 5)],
    "line_w2_horizontal": [("line", [10, 40, 110, 40], 0, -1, 2)],
    "line_w4_vertical": [("line", [60, 5, 60, 75], 0, -1, 4)],
    "line_short_dash": [("line", [20.25, 30.5, 26.75, 33.1], 0, -1, 2)],
    "line_white_on_black": [BLACK_BG, ("line", [5, 5, 115, 75], 255, -1, 3)],
    "polyline_w1": [("line", [10, 60, 40, 20.5, 70.2, 65, 110, 15], 0, -1, 1)],
    "polyline_w2": [("line", [10, 60, 40, 20.5, 70.2, 65, 110, 15], 0, -1, 2)],
    "polyline_w3": [("line", [10, 60, 40, 20.5, 70.2, 65, 110, 15], 0, -1, 3)],
    "polyline_icon": [("line", [70.4, 40.2, 66.6, 48.7, 74.4, 48.7, 70.6, 58.9], 0, -1, 3)],
    "points_dotted": [("points", [10, 110, 6, 40.5], 0, -1, 1)],
    "rect_fill_float": [("rectangle", [10.4, 10.6, 30.2, 30.9], 0, -1, 1)],
    "rect_white_on_black": [BLACK_BG, ("rectangle", [20, 20, 60, 50], 255, -1, 1)],
    "ellipse_outline_w3": [("ellipse", [10, 10, 90, 60], -1, 0, 3)],
    "ellipse_outline_float_w4": [("ellipse", [10.3, 5.6, 50.9, 44.2], -1, 0, 4)],
    "ellipse_outline_w2_small": [("ellipse", [20.5, 20.5, 31.5, 31.5], -1, 0, 2)],
    "ellipse_fill_black": [("ellipse", [80, 40, 119, 79], 0, -1, 1)],
    "ellipse_marker": [("line", [0, 40, 119, 40], 0, -1, 3), ("ellipse", [55, 35, 65, 45], 255, 0, 2)],
    "ellipse_cloud": [("ellipse", [20.6, 18.2, 60.6, 58.2], -1, 0, 3), ("ellipse", [23.6, 21.2, 57.6, 55.2], 255, -1, 1)],
    "polygon_triangle": [("polygon", [33.7, 36.2, 38.7, 45.2, 28.7, 45.2], 0, -1, 1)],
    "polygon_diamond": [("line", [0, 32, 119, 32], 0, -1, 2), ("polygon", [60, 20, 72, 32, 60, 44, 48, 32], 255, 0, 2)],
    "rounded_small": [("rounded_rectangle", [10.5, 10, 60.5, 32, 4], 0, -1, 1)],
    "rounded_float": [("rounded_rectangle", [70.3, 40.1, 110.6, 62.9, 4], 0, -1, 1)],
    # Negative coordinates: (int) truncates toward zero, so a view must not offset before it.
    "neg_line_w5": [("line", [-14.72, 24, 136.65, 77.6], 0, -1, 5)],
    "neg_ellipse_outline_w4": [("ellipse", [-9.75, 14, 30.25, 63.2], -1, 0, 4)],
    "neg_polygon_rounded": [("polygon", [-12.6, 70.4, 40.3, -8.7, 60.2, 75.5], 0, -1, 1),
                            ("rounded_rectangle", [-6.5, -3.5, 30.5, 20.5, 6], 255, -1, 1)],
}


def apply(d: ImageDraw.ImageDraw, op) -> None:
    kind, v, fill, outline, width = op
    f = None if fill < 0 else fill
    o = None if outline < 0 else outline
    if kind == "line":
        d.line(list(zip(v[0::2], v[1::2])), fill=f, width=width)
    elif kind == "points":
        for x in range(int(v[0]), int(v[1]), int(v[2])):
            d.point((x, v[3]), fill=f)
    elif kind == "rectangle":
        d.rectangle(v, fill=f, outline=o, width=width)
    elif kind == "ellipse":
        d.ellipse(v, fill=f, outline=o, width=width)
    elif kind == "polygon":
        d.polygon(list(zip(v[0::2], v[1::2])), fill=f, outline=o, width=width)
    elif kind == "rounded_rectangle":
        d.rounded_rectangle(v[:4], v[4], fill=f, outline=o, width=width)
    else:
        raise ValueError(kind)


def c_double(x: float) -> str:
    return repr(float(x))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    for name, ops in CASES.items():
        img = Image.new("L", (W, H), 255)
        d = ImageDraw.Draw(img)
        for op in ops:
            apply(d, op)
        img.point(lambda p: 255 if p > THRESHOLD else 0).convert("1").save(OUT / f"{name}.pbm")
        cops = ", ".join(
            "{\"%s\", %d, {%s}, %d, %d, %d}" % (k, len(v), ", ".join(c_double(x) for x in v), fi, ou, wi)
            for k, v, fi, ou, wi in ops)
        rows.append("    {\"%s\", %d, {%s}}," % (name, len(ops), cops))
    HEADER.write_text(
        "#pragma once\n// Generated by tools/ref_primitives.py; do not edit.\n"
        "struct PrimOp { const char* kind; int n; double v[16]; int fill, outline, width; };\n"
        "struct PrimCase { const char* name; int n_ops; PrimOp ops[3]; };\n"
        f"static const int PRIM_W = {W}, PRIM_H = {H};\n"
        "static const PrimCase PRIM_CASES[] = {\n" + "\n".join(rows) + "\n};\n")
    print(f"wrote {len(CASES)} cases")


if __name__ == "__main__":
    main()
